### ISSUE TITLE
[Study] CI/CD 실습 공부

### ISSUE THREAD

**Issue by saumonrose08** [nhnacademy-aiot2-javame/template-repo#15]
# 📚 공부 기록 - {{CI/CD 실습 공부}}

- 📅 날짜: {{2025-04-09}}
- ✍️ 작성자: {{임성인}}

---

## ✨ 오늘의 내용 요약
{{로컬에서 SSH 키를 생성하고 GitHub Actions를 통해 원격 서버에 배포되는 CI/CD 파이프라인을 구축하는 실습입니다.}}

---

## 📖 상세 내용

개인 로컬 환경에서 키를 생성하기 위해 터미널에서 작업합니다

---

### 1. 🔑 SSH 키 생성 및 서버 등록  

1. 로컬에서 작업 폴더 생성:
   ```bash
   mkdir keygen
   cd keygen
   ```

2. SSH 키 생성 (모두 Enter):
   ```bash
   ssh-keygen -t rsa -f ./github_rsa
   ```

   > 생성 파일: `github_rsa` (개인키), `github_rsa.pub` (공개키)

3. 원격 서버에서 공개키 등록:
   ```bash
   cat ~/github_rsa.pub >> ~/.ssh/authorized_keys
   ```

4. 서버에 있는 `github_rsa.pub`는 삭제합니다.

5. 로컬 개인키 권한 설정:
   ```bash
   chmod 400 github_rsa
   ```

6. SSH 접속 확인:
   ```bash
   ssh -i github_rsa -p 8822 aiot2-team3@s2.java21.net
   ```

---

### 2. 🚀 GitHub Actions 설정  

1. GitHub에 **리포지토리 생성 후 클론**합니다.

2. `Settings > Secrets and variables > Actions` 에 다음 항목을 등록:

   - `SSH_ID`: 원격 서버 접속 ID  
   - `SSH_IP`: 원격 서버 IP  
   - `SSH_KEY`: 로컬의 개인키 (`github_rsa`)  
   - `SSH_PORT`: 포트 번호 (예: 8822)

3. `Actions` 탭에서 **New workflow > Java with Maven** 선택 후 `maven.yml` 파일 수정:

   ```yml
   - name: upload file
     uses: appleboy/scp-action@v0.1.7
     with:
       host: ${{ secrets.SSH_IP }}
       username: ${{ secrets.SSH_ID }}
       key: ${{ secrets.SSH_KEY }}
       port: ${{ secrets.SSH_PORT }}
       source: "target/*.jar"
       target: "~/test/"
       rm: false

   - name: execute shell script
     uses: appleboy/ssh-action@master
     with:
       host: ${{ secrets.SSH_IP }}
       username: ${{ secrets.SSH_ID }}
       key: ${{ secrets.SSH_KEY }}
       port: ${{ secrets.SSH_PORT }}
       script_stop: true
       script: "test/startup.sh"
   ```

4. `application.properties`에서 서버 포트를 지정하고 변경사항을 commit합니다.

5. Push 후 GitHub Actions에서 Workflow가 자동 실행되고, 배포 성공 여부를 확인합니다.
